import { CustomerGender } from '@/modules/customers/domain/interfaces/customer-gender.interface';
import { FormField } from '@/modules/customers/domain/interfaces/form-field.interface';
import { Language } from '@/modules/customers/domain/interfaces/language.interface';
import { PasswordField } from '@/modules/customers/domain/interfaces/password-field.interface';
import { TextField } from '@/modules/customers/domain/interfaces/text-field.interface';

export interface RegistrationForm {
  customerPersoncode: TextField;
  customerMonthlyIncome: TextField;
  customerGender: CustomerGender;
  customerBirthday: TextField;
  customerPassword: PasswordField;
  agb: FormField;
  newsletter: FormField;
  dataUsage: FormField;
  language: Language;
  customerLastname: TextField;
  customerFirstname: TextField;
  customerPhone: TextField;
  customerEmail: TextField;
  customerStreet: TextField;
  customerHousenumber: TextField;
  customerFlatnumber: TextField;
  customerCity: TextField;
  customerZip: TextField;
  customerStreet2: TextField;
  customerHousenumber2: TextField;
  customerFlatnumber2: TextField;
  customerCity2: TextField;
  customerZip2: TextField;
  contactLastname: TextField;
  contactFirstname: TextField;
  contactPhone: TextField;
  contactEmail: TextField;
  contactStreet: TextField;
  contactCity: TextField;
  contactZip: TextField;
  jobName: TextField;
  jobPhone: TextField;
  jobPosition: TextField;
  jobStreet: TextField;
  jobHousenumber: TextField;
  jobFlatnumber: TextField;
  jobCity: TextField;
  jobZip: TextField;
  documentNumber: TextField;
  loanAmount: TextField;
  loanTerm: TextField;
  loanPromotion: TextField;
  customerMapping: TextField;
  bankIban: TextField;
}
